<h2>Upload a Photo</h2>

<form method="POST" name="gallery" id="gallery" enctype="multipart/form-data">
    <div class="form-group">
        <label for="photo">Choose a photo</label>
        <br>
        <input type="file" name="photo" required>
    </div>
    <br>
    <div class="form-group">
        <input type="submit" name="submit" id="submitbutton" value="Upload">
    </div>

    <br>
    <a href="<?= $this->url('gallery') ?>">Back to gallery</a>
</form>
